"""
Report generator - HTML, JSON, Excel, PDF, and SARIF v2.1.0 (CI/CD integration)
"""
import io
import json
from datetime import datetime
from typing import Optional
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, PatternFill, Alignment

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm, mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, HRFlowable
    )
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#d97706",
    "low": "#2563eb",
    "info": "#6b7280",
}

SARIF_LEVEL_MAP = {
    "critical": "error",
    "high": "error",
    "medium": "warning",
    "low": "note",
    "info": "note",
}


def generate_html_report(scan) -> str:
    findings_rows = ""
    for f in getattr(scan, "findings", []):
        sev = str(f.severity.value) if hasattr(f.severity, "value") else str(f.severity)
        color = SEVERITY_COLORS.get(sev, "#6b7280")
        findings_rows += f"""<tr>
            <td><span style="color:{color};font-weight:600;text-transform:uppercase">{sev}</span></td>
            <td>{f.category}</td>
            <td><strong>{f.title}</strong></td>
            <td>{f.description}</td>
            <td>{f.remediation}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>SentinelWP Security Report - {scan.target_url}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:'Segoe UI',Arial,sans-serif;color:#1e293b;padding:40px;max-width:1200px;margin:0 auto;background:#fff}}
h1{{font-size:24px;color:#0f172a;margin-bottom:4px}}
h2{{font-size:18px;color:#334155;margin:24px 0 12px;border-bottom:2px solid #e2e8f0;padding-bottom:6px}}
.meta{{color:#64748b;font-size:13px;margin-bottom:24px}}
.summary-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:16px 0 32px}}
.card{{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;text-align:center}}
.card-value{{font-size:28px;font-weight:700;color:#0f172a}}
.card-label{{font-size:12px;color:#64748b;margin-top:4px}}
table{{width:100%;border-collapse:collapse;font-size:13px}}
th{{background:#f1f5f9;text-align:left;padding:10px 8px;font-weight:600;border-bottom:2px solid #e2e8f0}}
td{{padding:8px;border-bottom:1px solid #f1f5f9;vertical-align:top}}
tr:hover{{background:#f8fafc}}
.footer{{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8;text-align:center}}
</style>
</head>
<body>
<h1>SentinelWP — WordPress Security Report</h1>
<p class="meta">Target: {scan.target_url} | Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | Scan ID: {scan.id[:8]}</p>
<div class="summary-grid">
  <div class="card"><div class="card-value">{scan.score if scan.score is not None else 'N/A'}</div><div class="card-label">Risk Score (0-100)</div></div>
  <div class="card"><div class="card-value">{scan.grade or 'N/A'}</div><div class="card-label">Grade</div></div>
  <div class="card"><div class="card-value">{len(scan.findings)}</div><div class="card-label">Total Findings</div></div>
  <div class="card"><div class="card-value">{'Yes' if scan.is_wordpress else 'No'}</div><div class="card-label">WordPress Detected</div></div>
</div>
<h2>Findings Detail</h2>
<table>
<thead><tr><th>Severity</th><th>Category</th><th>Title</th><th>Description</th><th>Remediation</th></tr></thead>
<tbody>{findings_rows}</tbody>
</table>
<div class="footer">Generated by SentinelWP — WordPress Security Sentinel</div>
</body>
</html>"""
    return html


def generate_json_report(scan) -> str:
    def f_to_dict(f):
        return {
            "id": f.id,
            "severity": f.severity.value if hasattr(f.severity, "value") else str(f.severity),
            "category": f.category,
            "title": f.title,
            "description": f.description,
            "confidence": f.confidence,
            "remediation": f.remediation,
            "reference": f.reference,
        }
    obj = {
        "scan_id": scan.id,
        "target_url": scan.target_url,
        "score": scan.score,
        "grade": scan.grade,
        "is_wordpress": scan.is_wordpress,
        "wp_version": scan.wp_version,
        "started_at": scan.started_at,
        "completed_at": scan.completed_at,
        "findings_count": len(scan.findings),
        "findings": [f_to_dict(f) for f in scan.findings],
    }
    return json.dumps(obj, indent=2, ensure_ascii=False)


def generate_sarif_report(scan) -> str:
    """
    Generate OASIS SARIF v2.1.0 format report for CI/CD integration (GitHub/GitLab).
    """
    rules = []
    results = []
    seen_rule_ids = set()

    for idx, f in enumerate(getattr(scan, "findings", [])):
        sev = f.severity.value if hasattr(f.severity, "value") else str(f.severity)
        level = SARIF_LEVEL_MAP.get(sev, "note")
        rule_id = f"SENTINEL-{f.category.upper()}-{abs(hash(f.title)) % 10000:04d}"

        if rule_id not in seen_rule_ids:
            seen_rule_ids.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": f.title.replace(" ", ""),
                "shortDescription": {"text": f.title},
                "fullDescription": {"text": f.description},
                "help": {"text": f.remediation or "Refer to security hardening guidelines."},
                "properties": {"tags": ["security", "wordpress", f.category]}
            })

        results.append({
            "ruleId": rule_id,
            "level": level,
            "message": {"text": f"{f.title}: {f.description}"},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": scan.target_url},
                    "region": {"startLine": 1}
                }
            }]
        })

    sarif_log = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemas/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "SentinelWP",
                    "version": "2.1.0",
                    "informationUri": "https://github.com/melillopietro/SentinelWP",
                    "rules": rules
                }
            },
            "results": results
        }]
    }

    return json.dumps(sarif_log, indent=2, ensure_ascii=False)


def generate_excel_report(scan) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"
    ws["A1"] = "SentinelWP Security Report"
    ws["A1"].font = Font(size=14, bold=True)
    ws.append([])
    ws.append(["Scan ID", scan.id])
    ws.append(["Target", scan.target_url])
    ws.append(["Score", scan.score])
    ws.append(["Grade", scan.grade])
    ws.append(["WordPress", "Yes" if scan.is_wordpress else "No"])
    ws.append(["WP Version", scan.wp_version or "Unknown"])
    ws.append(["Date", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")])

    ws2 = wb.create_sheet(title="Findings")
    headers = ["Severity", "Category", "Title", "Description", "Confidence", "Remediation", "Reference"]
    ws2.append(headers)
    header_fill = PatternFill(start_color="f1f5f9", end_color="f1f5f9", fill_type="solid")
    for cell in ws2[1]:
        cell.font = Font(bold=True)
        cell.fill = header_fill

    for f in scan.findings:
        sev = f.severity.value if hasattr(f.severity, "value") else str(f.severity)
        ws2.append([sev, f.category, f.title, f.description, f.confidence, f.remediation, f.reference])

    for sheet in wb.worksheets:
        for col in sheet.columns:
            col_letter = get_column_letter(col[0].column)
            max_len = max((len(str(c.value or "")) for c in col), default=10)
            sheet.column_dimensions[col_letter].width = min(60, max(12, max_len + 2))

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_pdf_report(scan) -> bytes:
    if not HAS_REPORTLAB:
        raise RuntimeError("ReportLab is required for PDF generation.")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=20, spaceAfter=6)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey)
    heading_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14, spaceBefore=16, spaceAfter=8)

    elems = []
    elems.append(Paragraph("SentinelWP — WordPress Security Report", title_style))
    elems.append(Paragraph(f"Target: {scan.target_url}", subtitle_style))
    elems.append(Paragraph(f"Date: {datetime.utcnow().strftime(chr(37)+'Y-'+chr(37)+'m-'+chr(37)+'d '+chr(37)+'H:'+chr(37)+'M UTC')} | Scan ID: {scan.id[:8]}", subtitle_style))
    elems.append(Spacer(1, 12))
    elems.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    elems.append(Spacer(1, 12))

    summary_data = [
        ["Risk Score", str(scan.score if scan.score is not None else "N/A")],
        ["Grade", scan.grade or "N/A"],
        ["Total Findings", str(len(scan.findings))],
        ["WordPress", "Yes" if scan.is_wordpress else "No"],
        ["WP Version", scan.wp_version or "Unknown"],
    ]
    t = Table(summary_data, colWidths=[4*cm, 8*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 16))
    elems.append(Paragraph("Findings", heading_style))

    findings_data = [["Severity", "Category", "Title", "Remediation"]]
    for f in scan.findings:
        sev = f.severity.value if hasattr(f.severity, "value") else str(f.severity)
        findings_data.append([
            sev.upper(),
            f.category,
            f.title[:80],
            (f.remediation or "")[:120]
        ])

    if len(findings_data) > 1:
        ft = Table(findings_data, colWidths=[2.2*cm, 2.8*cm, 5.5*cm, 6*cm], repeatRows=1)
        ft.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ]))
        elems.append(ft)
    else:
        elems.append(Paragraph("No findings.", styles["Normal"]))

    elems.append(Spacer(1, 24))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    elems.append(Paragraph("Generated by SentinelWP — WordPress Security Sentinel", subtitle_style))

    doc.build(elems)
    return buf.getvalue()
